craft_env_defaults:
  db_server: localhost
  db_database: "{{ site | underscore }}_{{ env }}"
  db_user: "{{ site | underscore }}"
  db_driver: mysql
  db_port: 3306
  db_table_prefix: craft
  composer_home: "{{ composer_home_path }}"
  environment: "{{ env }}"

site_env: "{{ craft_env_defaults | combine(project.env | default({}), vault_craft_sites[site].env) }}"
