craft_env_defaults:
  db_host: localhost
  db_name: "{{ site | underscore }}_{{ env }}"
  db_user: "{{ site | underscore }}"
  domain_current_site: "{{ project.site_hosts | map(attribute='canonical') | first }}"

site_env: "{{ craft_env_defaults | combine(project.env | default({}), vault_craft_sites[site].env) }}"
