craft_env_defaults:
  db_server: localhost
  db_database: "{{ item.key | underscore }}_{{ env }}"
  db_user: "{{ item.key | underscore }}"
  db_user_host: localhost
  db_driver: mysql
  db_port: 3306
  db_table_prefix: craft
  composer_home: "{{ composer_home_path }}"
  environment: "{{ env }}"

site_env: "{{ craft_env_defaults | combine(vault_craft_env_defaults | default({}), item.value.env | default({}), vault_craft_sites[item.key].env) }}"
site_hosts_canonical: "{{ item.value.site_hosts | map(attribute='canonical') | list }}"
site_hosts_redirects: "{{ item.value.site_hosts | selectattr('redirects', 'defined') | sum(attribute='redirects', start=[]) | list }}"
site_hosts: "{{ site_hosts_canonical | union(site_hosts_redirects) }}"
ssl_enabled: "{{ item.value.ssl is defined and item.value.ssl.enabled | default(false) }}"
ssl_stapling_enabled: "{{ item.value.ssl is defined and item.value.ssl.stapling_enabled | default(true) }}"
sites_use_ssl: "{{ craft_sites.values() | map(attribute='ssl') | selectattr('enabled') | list | count > 0 }}"

# For backward compatibility, to be removed in Trellis v2.
site_packagist_org_authentications:
  - { hostname: repo.packagist.com, username: token, password: "{{ vault_craft_sites[site].packagist_token | default('') }}" }
site_composer_authentications: "{{ vault_craft_sites[site].composer_authentications | default([]) }}"
composer_authentications: "{{ site_packagist_org_authentications + site_composer_authentications }}"
