apt_cache_valid_time: 86400
default_timezone: Etc/UTC
www_root: /srv/www
ip_whitelist:
  - "{{ lookup('pipe', 'curl -4 -s https://api.ipify.org') }}"

craft_env_defaults:
  db_host: localhost
  db_name: "{{ item.key | underscore }}_{{ env }}"
  db_user: "{{ item.key | underscore }}"

site_env: "{{ craft_env_defaults | combine(item.value.env | default({}), vault_craft_sites[item.key].env) }}"

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_wordpress_sites.*.*_salt    -- matches vault_wordpress_sites.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_mysql_root_password
  - vault_craft_sites
