---
- block:
  - name: Create databases for sites
    mysql_db:
      name: "{{ site_env.db_database }}"
      state: present
      login_host: "{{ site_env.db_server }}"
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
    no_log: true
    with_dict: "{{ craft_sites }}"

  - name: Create/assign database user to db and grant permissions
    mysql_user:
      name: "{{ site_env.db_user }}"
      password: "{{ site_env.db_password }}"
      host: "{{ site_env.db_user_host }}"
      append_privs: no
      priv: "{{ site_env.db_database }}.*:SELECT,INSERT,DELETE,UPDATE,CREATE,ALTER,INDEX,DROP,REFERENCES,LOCK TABLES"
      state: present
      login_host: "{{ site_env.db_server }}"
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
    no_log: true
    with_dict: "{{ craft_sites }}"

  when: site_uses_local_db and item.value.db_create | default(true)
