---
- include: database.yml
  tags: craft-setup-database
- include: self-signed-certificate.yml
  tags: craft-setup-self-signed-certificate

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ craft_sites }}"

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ craft_sites }}"

- name: Create Craft php-fpm configuration file
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.0/fpm/pool.d/craft.conf
  notify: reload php-fpm

- name: Disable default PHP-FPM pool
  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled
  args:
    creates: /etc/php/7.0/fpm/pool.d/www.disabled
  when: disable_default_pool | default(true)
  notify: reload php-fpm

- include: nginx.yml
  tags: craft-setup-nginx
