---
- import_tasks: directories.yml
  tags: craft-install-directories

- import_tasks: dotenv.yml
  tags: dotenv

- name: Add known_hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  become: no
  with_items: "{{ known_hosts | default([]) }}"

- include_tasks: tasks/composer-authentications.yml
  vars:
    site: "{{ item.key }}"
    working_dir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  no_log: true
  with_dict: "{{ craft_sites }}"

- name: Install Dependencies with Composer
  composer:
    no_dev: no
    optimize_autoloader: no
    working_dir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  become: no
  with_dict: "{{ craft_sites }}"
