---
- include: directories.yml
  tags: craft-install-directories

- name: Create .env file
  template:
    src: "env.j2"
    dest: "/tmp/{{ item.key }}.env"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
  with_dict: "{{ craft_sites }}"

- name: Copy .env file into web root
  command: rsync -ac --info=NAME /tmp/{{ item.key }}.env {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/.env
  with_dict: "{{ craft_sites }}"
  register: env_file
  changed_when: env_file.stdout == item.key + '.env'
