# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `craft_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

craft_sites:
  example.com:
    site_hosts:
      - example.com
    local_path: ../site # path targeting local Craft site directory (relative to Ansible root)
    repo: git@github.com:example/example.com.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Craft site directory in your repo
    branch: master
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
