---
- name: Add PHP 7.0 PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes

- name: Install PHP 7.0
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_dict: "{{ php_extensions }}"

- name: Start php7.0-fpm service
  service:
    name: php7.0-fpm
    state: started
    enabled: true

- name: PHP configuration file
  template:
    src: php.ini.j2
    dest: /etc/php/7.0/fpm/php.ini
  notify: reload php-fpm
